apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kuberenetes-workshop-21-ugi
  name: kuberenetes-workshop-21-ugi
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: kuberenetes-workshop-21-ugi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kuberenetes-workshop-21-ugi
    spec:
      containers:
      - image: gcr.io/kubernetes-workshop-21-ugi/upenderg/kubernetes-workshop-21:f0ccba5b29c84489d2cf54a1567fc5784c271ab8
        imagePullPolicy: IfNotPresent
        name: kuberenetes-workshop-21-ugi
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
